before_install: cd Practice
sudo: required
services:
  - docker
script:
  - docker build -t practice .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag practice $DOCKER_USER/cloud_practice
  - docker push $DOCKER_USER/cloud_practice